apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prism-web
  namespace: prism-servers
subjects:
- kind: ServiceAccount
  name: sa-prism-web
roleRef:
  kind: Role
  name: prism-server-manager
  apiGroup: rbac.authorization.k8s.io
