apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prism-server-manager
  namespace: prism-servers
rules:
  - apiGroups:
      - prism-hosting.ch
    resources:
      - prismservers
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - "*"
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - "*"
