apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prism-web-certificate
  namespace: prism-servers
spec:
  secretName: prism-web-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - "prism.siegrist.io"
