apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: prism-web
  namespace: prism-servers
spec:
  encryptedData:
    master_key: AgC19617sppW/mgXsoVox8iwcKuaY4RJJ+WOXOieT0XlpoktXZuXNngjS00IwfZr/kc2yaFw11mC3/kQJVNrsJXDEFRr1/cuQgROg9LDTZB3bjRPi1RHuUSyzvslcT9jp69ThFThOCSwP2uFo3jUvLo4/gTQ8MaRUPfxi7k2s7+cR1e/ckK5Cw9Hut7FVcYIPdkTZHB/K3Hff39nj3/qaRblMsD8IO2vDexmmbU8KaU8a0SfPbYor9oAzLQQqEZkhmTBuWNN5oIPmRzGN3L3F1U+EeYVQlhvJ2MqPBZ7Mq1OzszRAvFSEMjLJOGLSroTe1/NWIpV8/vVqp+grtp0a+i05fZs+wBem7TeIRqywv3yIPCE/D/YFs0sFDeP5VrC8cSN3mQX32J/jdqA0vEkmrAj4WT7mwUY+W3Oo6bO5jmPCVE/vhdDLACjjaYO1xv9kOMnzj+Z+d2YKn/GshfDKAFA4vUhTZmgt6AlCnQ+7qkv/ErX31WBLDuQfnaBSIdYMkhTOulcH5S7d4KyuLZhJeaEm9ECoUiJFqLMPlzEy2DIq3bIcO/XZmv/3UAMTw1VM/zVsgbvNx53nGHRHtFZ5OtCCj/paNM6qDRUlx61CcHB7q0LjZYBq/jpF57FGZa8JfvXTdMpm7T2amqXV4WQLqpipra30Josxlc47O5DXXgTLZk4s9PRnC0dte/06f3N1UfxvI+a3Gi0JGdmgAPmvCYZlJS8d7qkrPtbew+Ll8t+2A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: prism-web
      namespace: prism-servers

